version: '2'

services:
  sms-bot:
    build: .
    container_name: sms-bot
    ports:
      - 3000:3000
    volumes:
      - ./src/:/usr/src/app/src/
      - ./test/:/usr/src/app/test/
    environment:
      - TOKEN
      - DISABLE_REDIS
    links:
      - redis

  redis:
    image: redis:3.0
