version: '2'
services:
  sms-bot:
    build: ./sms-bot/
    container_name: sms-bot
    ports:
      - 3000:3000
    volumes:
      - ./sms-bot/src/:/usr/src/app/src/
      - ./sms-bot/test/:/usr/src/app/test/
    environment:
      - TERM=xterm-256color
      - TOKEN
      - DISABLE_REDIS
      - MESSENGER_VALIDATION_TOKEN
      - MESSENGER_PAGE_ACCESS_TOKEN
      - LETSENCRYPT_HOST=sms.vesselstech.com
      - LETSENCRYPT_EMAIL=kevindoveton@me.com
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=sms.vesselstech.com
    links:
      - redis
      - mock-service
      - mongo

  sms-ui:
    build: ./sms-ui/
    # command: './run_dev.sh'
    command: 'tail -f /dev/null'
    ports:
      - 3002:3002
    volumes:
      - ./sms-ui/:/usr/src/app/
    environment:
      - VIRTUAL_HOST=console.vesselstech.com
      - SMS_BOT_BASE_URL=http://localhost:3000
    links:
      - mock-service

  mock-service:
    build: './mock-service/'
    container_name: mock-service
    ports:
      - 3001:3001
    volumes:
      - ./mock-service/:/usr/src/app/
    environment:
      - VIRTUAL_HOST=mock-service.vesselstech.com
    links:
      - mongo

  mongo:
    image: mongo:3.4.3
    volumes:
      - ./.mongo:/data/db

  redis:
    image: redis:3.0

  sms-utils:
    build: './sms-utils/'
    environment:
      - SEED_FROM_S3
      - SCHEDULE_S3_BACKUPS
      - SEED_LOCAL=true
      - SCHEDULE_LOCAL_BACKUPS=true
    links:
      - mongo
    volumes:
      - ./sms-utils:/usr/src/app/
      # - ./sms-utils/seed:/seed-data
      - ./sms-utils/backups:/backups
