version: '2'

services:
  sms-bot:
    build: .
    container_name: sms-bot
    ports:
        - 3000:3000
    networks:
        - code-network
    volumes:
        - ./src/:/usr/src/app/src/
    environment:
        - TOKEN
    links:
      - redis

  redis:
    image: redis:3.0


networks:
  code-network:
    driver: bridge
