version: '2'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /certs:/etc/nginx/certs
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
        networks:
            - code-network

    nginx-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-letsencrypt
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
            - nginx-proxy
        networks:
            - code-network

    messenger-bot:
        build: .
        image: messenger-bot
        expose:
            - 3000
        networks:
            - code-network
        environment:
            - "VIRTUAL_HOST=dev1.kdoveton.com"
            - "LETSENCRYPT_HOST=dev1.kdoveton.com"
            - "LETSENCRYPT_EMAIL=kevindoveton@me.com"
            - "HTTPS_METHOD=redirect"
            - "VIRTUAL_PORT=3000"
            - MESSENGER_APP_SECRET
            - MESSENGER_PAGE_ACCESS_TOKEN
            - MESSENGER_VALIDATION_TOKEN
            - SERVER_URL

networks:
    code-network:
        driver: bridge
        