#!/bin/bash

source .env

MESSENGER_APP_SECRET=$MESSENGER_APP_SECRET MESSENGER_PAGE_ACCESS_TOKEN=$MESSENGER_PAGE_ACCESS_TOKEN MESSENGER_VALIDATION_TOKEN=$MESSENGER_VALIDATION_TOKEN SERVER_URL=$SERVER_URL docker-compose up
