
export const REQUEST_SERVICE_LOGS = 'REQUEST_SERVICE_LOGS';
export const RECEIVE_SERVICE_LOGS = 'RECEIVE_SERVICE_LOGS';
export const INVALIDATE_SERVICE_LOGS = 'INVALIDATE_SERVICE_LOGS';
export const SELECT_SERVICE = 'SELECT_SERVICE';
export const REQUEST_SERVICE_CONFIGURATION = 'REQUEST_SERVICE_CONFIGURATION';
export const RECEIVE_SERVICE_CONFIGURATION = 'RECEIVE_SERVICE_CONFIGURATION';
export const INVALIDATE_SERVICE_CONFIGURATION = 'INVALIDATE_SERVICE_CONFIGURATION';
